apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Deployment
metadata:
  name: task-pv-pod
spec:
  replicas: 0
  selector:
    matchLabels:
      app: task-pv-pod
  template:
    metadata:
      labels:
        app: task-pv-pod
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: task-pv-container
          image: python
          ports:
            - containerPort: 8888
              name: "jupyterlab"
          volumeMounts:
            - mountPath: "/opt/app-root/src/"
              name: task-pv-storage
---
kind: Service
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  ports:
    - name: http-8888
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: task-pv-pod
