kind: Deployment
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-pv-pod
  template:
    metadata:
      labels:
        app: task-pv-pod
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: task-pv-container
          image: jupyterlab-image:latest
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          volumeMounts:
            - mountPath: "/opt/app-root/src/"
              name: task-pv-storage
---
kind: Service
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: task-pv-pod
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

