kind: Service
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  selector:
    app: task-pv-pod
  ipFamilies:
    - IPv4
  ports:
    - name: 8888-tcp
      protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: Route
metadata:
  name: task-pv-pod
  spec:
    to:
      kind: Service
      name: task-pv-pod
      weight: 100
    port:
      targetPort: 8888
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyterlab-pvc
spec:
  accessModes:
    -ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
    storageClassName: ocs-external-storagecluster-ceph-rbd
---
kind: Deployment
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-pv-pod
  template:
    metadata:
      labels:
        app: task-pv-pod
    spec:
      containers:
        - name: task-pv-container
          image: jupyterlab-image:latest
          ports:
          - containerPort: 8888
            protocol: TCP
          volumeMounts:
            - mountPath: "/opt/app-root/src/"
              name: task-pv-storage
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: jupyterlab-pvc


