kind: Service
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  selector:
    app: task-pv-pod
  ipFamilies:
    - IPv4
  ports:
    - name: 8888-tcp
      protocol: TCP
      port: 8888
      targetPort: 8888
---
kind: Deployment
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-pv-pod
  template:
    metadata:
      labels:
        app: task-pv-pod
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: jupyterlab-persistente
      containers:
        - name: task-pv-container
          image: jupyterlab-image:latest
          ports:
          - containerPort: 8888
            protocol: TCP
          volumeMounts:
            - mountPath: "/opt/app-root/src/"
              name: task-pv-storage



